In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

## 数组对象

### 1. 向量加法

In [2]:
def numpySum(n):
    a = np.arange(n) ** 2
    b = np.arange(n) ** 3
    c = a + b
    return c

In [6]:
tmp = numpySum(3)
print(tmp[0:-1])

[0 2]


## numpy基础

### 2.1 numpy数组对象

In [7]:
a = np.arange(5)
a.dtype

dtype('int32')

In [8]:
print(a)
print(a.shape)

[0 1 2 3 4]
(5,)


### 2.2 多维数组

In [9]:
a = np.array([np.arange(2), np.arange(2)])

In [11]:
print(a)
print("shape", a.shape)

[[0 1]
 [0 1]]
shape (2, 2)


In [13]:
# 数据类型，单个元素占用字节数
print('数据类型', a.dtype)
print(a.dtype.itemsize)

数据类型 int32
4


In [15]:
t = np.dtype('f8')
print(t.char)
print(t.type)

d
<class 'numpy.float64'>


### 2.3 自定义数据类型
> 定义一个对象：例如商品（id,name,desc...）

In [17]:
t = np.dtype([('name', np.str_, 40), ('numitems', np.int32), ('price', np.float32)])

In [19]:
t

dtype([('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')])

In [20]:
t['name']

dtype('<U40')

In [21]:
item = np.array([('meaning of life dvd', 42, 3.14),
                ('butter', 13, 2.72)], dtype=t)

In [26]:
print(item[1])
print('name:', item[0]['name'])

('butter', 13,  2.72000003)
name: meaning of life dvd


### 2.5 多维数组的切片和索引

In [28]:
b = np.arange(24).reshape(2,3,4)

In [29]:
print(b.shape)

(2, 3, 4)


In [30]:
print(b[:,:,:])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [35]:
print(b[0, 1, ::1])
print(b[0, 1, ::2])

[4 5 6 7]
[4 6]


### 2.6 改变数组维度

In [42]:
# ravel 将数组展平 ==返回原对象的引用，修改引用，影响原对象==
b.ravel()
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [43]:
# flatten 将数组展平 ==返回新的对象==
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [50]:
# 修改原始对象维度
b.shape = (6,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [49]:
# 矩阵转置
b.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [53]:
# reshape 返回新的修改后对象 / resize 返回原始对象
a = b.reshape(2, 12)
print(b, a)

a = b.resize(4,6)
print(b, a)  # a = None

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] [[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] None


### 2.8 组合数组

In [54]:
a = np.arange(9).reshape(3,3)

In [56]:
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [57]:
b = 2 * a
print(b)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [58]:
# 水平组合, 增加第二个维度长度，其他不变
np.hstack((a, b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [59]:
np.concatenate((a, b), axis=1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [60]:
# 垂直组合, 增加第一个维度长度，其他不变
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [64]:
np.concatenate((a, b), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [65]:
# 深度组合, 增加了一个维度，并在最小维度上1 1 对应
np.dstack((a,b))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

In [66]:
# 列组合
# 对于一维数组，按列方向组合
oned = np.arange(2)
print(oned)

[0 1]


In [67]:
twice_oned = 2 * oned
print(twice_oned)

[0 2]


In [68]:
np.column_stack((oned, twice_oned))

array([[0, 0],
       [1, 2]])

In [69]:
# 对于二维数组，效果与hstack相同
np.column_stack((a,b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [70]:
np.column_stack((a, b)) == np.hstack((a, b))

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]], dtype=bool)

### 2.9 数组的分割

### 2.10 分割数组

In [73]:
# 水平分割
a = np.arange(9).reshape((3,3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [74]:
np.hsplit(a, 3)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [76]:
np.split(a, 3, axis=1)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [77]:
# 垂直分割
np.vsplit(a, 3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [80]:
np.split(a, 3, axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [81]:
# 深度分割
c = np.arange(27).reshape(3 , 3, 3)
print(c)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [82]:
np.dsplit(c, 3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]), array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

### 2.11 数组的属性

In [85]:
# ndim 数组轴个数
b.ndim

2